"""empty message

Revision ID: 88c53978603c
Revises: 50bee1a88392
Create Date: 2023-01-23 12:48:53.411450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c53978603c'
down_revision = '50bee1a88392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_process_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_task_name')
        batch_op.create_index(batch_op.f('ix_task_main_process_id'), ['main_process_id'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_task_main_process_id'))
        batch_op.create_index('ix_task_name', ['name'], unique=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('main_process_id')

    # ### end Alembic commands ###
