"""weight table

Revision ID: cb1e83f55411
Revises: 
Create Date: 2022-10-18 18:25:01.400174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1e83f55411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.Integer(), nullable=True),
    sa.Column('yard', sa.String(length=8), nullable=True),
    sa.Column('rbook', sa.Integer(), nullable=True),
    sa.Column('typ', sa.String(length=1), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('pid', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_index(op.f('ix_weight_mtime'), 'weight', ['mtime'], unique=True)
    op.create_index(op.f('ix_weight_yard'), 'weight', ['yard'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_yard'), table_name='weight')
    op.drop_index(op.f('ix_weight_mtime'), table_name='weight')
    op.drop_table('weight')
    # ### end Alembic commands ###
